---
  name: "header"
  version: "0.0.1"
  description: "Site header"
  author: "Ginetta"
  data:
    primary:
      -
        title: "Home"
        href: "./"
      -
        title: "Kompetenzen"
        href: "./kompetenzen.html"
      -
        title: "Projekte"
        href: "./projekte.html"
      -
        title: "Arbeiten bei uns"
        href: "./arbeiten.html"
      -
        title: "Über uns"
        href: "./uber_uns.html"
      -
        title: "Aktuelles"
        href: "./aktuelles.html"
    secondary:
      -
        title: "Offene Stellen"
        href: ""
        icon: "offene-small"
      -
        title: "Ansprechpartner"
        href: "team.html"
        icon: "contact-small"
      -
        title: "Anfahrt"
        href: ""
  options:
    active:
      values: [Home, Kompetenzen, Projekte, Arbeiten bei uns, Über uns, Aktuelles]
      default: "Home"
