---
  name: "footer"
  version: "0.0.1"
  description: "Standard footer"
  author: "Ginetta"
  data:
    copyright: '© Basler & Hofmann 2015'
    languages:
      - text: 'DE'
        href: '#'
        active: true
      - text: 'FR'
        href: '#'
      - text: 'EN'
        href: '#'
    links:
      - text: 'Impressum'
        href: '#'
      - text: 'Service Links'
        href: '#'
  options: {}
