---
  name: "filter"
  version: "0.0.1"
  description: "Filter component"
  author: "Ginetta"
  data:
    label: "Filter nach "
    filterValue: Kompetenz
    filterAttribute: expertise
    itemGroups:
      - label: 'A'
        items:
          - Altlasten
          - Asbest und Gebäudeschadstoffe
      - label: 'B'
        items:
          - Bahnbau
          - Bahnhöfe
          - Bahntechnik
          - Baudynamik
          - Baugruben
          - Baugrund

  options: {}
