---
  name: "item-current"
  version: "0.0.1"
  description: "Current item component"
  author: "Ginetta"
  data:
    title: "Schule als Gestaltungs-, Lern und Lebensraum am 12. März 2015"
    label: "Veranstaltung"
    href: "#"
    date: "27.03.2015"
    location: ""
    imgSrc: false
  options:
    size:
      values: ['small', 'medium', 'large', 'box']
      default: 'small'
    icon:
      values: ['news', 'event', 'publication', false]
      default: 'news'
    isExternal:
      values: [true, false]
      default: false
    download:
      values: [false, '.pdf']
      default: false
    background:
      values: ["light-pink", "light-blue", "light-green", false]
      default: "light-pink"
    border:
      values: [false, true]
      default: false
