---
  name: "item-current"
  version: "0.0.1"
  description: "Example component"
  author: "Ginetta"
  data:
    title: "Schule als Gestaltungs-, Lern und Lebensraum am 12. März 2015"
    type: "Veranstaltungen"
  options:
    hasLabel:
      values: [true, false]
      default: false
