---
  name: "item-current"
  version: "0.0.1"
  description: "Current item component"
  author: "Ginetta"
  data:
    title: "Schule als Gestaltungs-, Lern und Lebensraum am 12. März 2015"
    label: "Veranstaltung"
    href: "#"
    date: "27.03.2015"
  options:
    size:
      values: ['small', 'medium', 'large', 'box']
      default: 'small'
    icon:
      values: ['document', 'calendar', 'publikation']
      default: 'document'
    isExternal:
      values: [true, false]
      default: false
