---
  name: "button"
  version: "0.0.1"
  description: "All the skeleton's buttons"
  author: "Ginetta"
  data:
    text: "default label"
    href: "#"
  options:
    color:
      values:
        - "dark"
        - "light"
      default: "dark"
