---
  name: "button"
  version: "0.0.1"
  description: "All the skeleton's buttons"
  author: "Ginetta"
  data:
    label: "default label"
  options:
    size:
      values:
        - "big"
        - "medium"
        - "small"
      default: "medium"
    color:
      values:
        - "red"
        - "blue"
        - "green"
      default: "green"
    corners:
      values:
        - "rounded"
        - "circle"
        - "square"
      default: "rounded"
    disabled:
      values:
        - true
        - false
      default: false
