---
  name: "listing"
  version: "0.0.1"
  description: "Listing component"
  author: "Ginetta"
  data:
    title: "Rückblick"
  options:
    showTitle:
      values: [false, true]
      default: false
