---
  name: "fullwidth-image"
  version: "0.0.1"
  description: "Example component"
  author: "Ginetta"
  data:
    imgSrc: "http://static.pexels.com/wp-content/uploads/2014/10/long-road-straight-3131.jpg"
  options:
    size:
      values: [normal, big]
      default: normal
    content:
      values: [true, false]
      default: true
