---
  name: "section"
  version: "0.0.1"
  description: "A section is a module that has a title and transcluded content. Optionally it also contains a button"
  author: "Ginetta"
  data:
    title: "Projekte im Fokus"
    buttonText: "Weitere Projekte"
    buttonHref: "#"
    id: ""
  options:
    background:
      values: ["white", "light-pink", "light-blue", "light-green"]
      default: "white"
    containerSize:
      values: ['s', 'm', 'l']
      default: 'm'
    content:
      values: [true, false]
      default: true
