---
  name: "item-contact"
  version: "0.0.1"
  description: "Contact item component"
  author: "Ginetta"
  data:
    imgSrc: "http://placehold.it/217x145/dc2856/FFFFFF/.png&text=Image1"
    firstname: "Hans"
    lastname: "Muster"
    role: "Leitender Experte"
    region: "Murten"
    phone: "044 387 13 19"
    email: "test@example.com"
    attributes:
      expertises: 'Bahnbau'
  options: {}
